### PR TITLE
Added basic page about design system

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
# Description

Adds a design system page for designing interfaces on Corpus

## Dependencies

Dependencies on CDN links to DaisyUI and Tailwind CSS

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

- [ ] Tested locally

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

image

### CODE REVIEW

**Comment by nishant-nayak** [comment]
The tests seem to be failing. It looks like you've defined the app `internal` (in `internal.apps.InternalConfig`), but I don't see any code related to the `internal` app. Is that something you forgot to push or a framework you're using?

**Comment by anirudhprabhakaran3** [comment]
Yeah kinda weird, need to figure it out. The same tests are running on my local system and passing, need to see why this is failing.

**Comment by nishant-nayak** [comment]
Closing this PR because the entire design system is changing with the introduction of SvelteKit and Storybook from #12 . Please make a new branch off the latest `main` when you're working on the updated design system. @anirudhprabhakaran3

**Comment by anirudhprabhakaran3** [comment]
Yup, will do. Deleting branch too!

**Pull request closed without merging**
