### PR TITLE
Bring back to Django

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
Revert everything back so that we have a pure Django application.

### CODE REVIEW

**Review by nishant-nayak — COMMENTED** [review]
Do we need the `nginx` configured for development? If you think we do, the rest of the changes look good to me.

**Comment by anirudhprabhakaran3** [comment]
Yeah, am removing that. Also, I'm actually planning to interchange the production and normal docker compose files, so that we have to run `docker compose` without the `-f` flag. Would make developers' lives easier.

**Review by nishant-nayak — CHANGES_REQUESTED** [review]
Please update the README with updated commands for Docker Development, remove unnecessary sections (like frontend), etc.

**Review by nishant-nayak — APPROVED** [review]
LGTM! Thanks for adding the additional documentation for contributors.

**Pull request merged**
