### PR TITLE
[UI] Add select2 to make select searchable

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
# Description

Make select fields searchable. This will be most useful in the case where we have a lot of options to choose from (e.g. selecting exec members)

## Dependencies

- [select2](https://select2.org/)

## Type of Change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Visual testing!

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nishant-nayak** [comment]
It looks like we have a grand total of 0 select fields across Corpus today. Do you know of any select fields that I can test this with? If not, I think we should hold onto this PR until we actually need the functionality.

It'll be more annoying if we merge this now and later on want to revert, we'll have to hunt for this PR and make a reverting fix.

**Comment by anirudhprabhakaran3** [comment]
Yeah so, one place we can use this right now is in Virtual Expo, where reviewers are assigned. Currently on prod, it looks like this:

image

Its nearly impossible to select in this scenario.

Also for the groups dashboard, I am planning to make a UI where you can add members to a group, so that will also need this sort of a selection thing.

Although I agree that maybe this sort of a global change is not required - we just add that snippet in the places that we need it and no where else.

**Comment by nishant-nayak** [comment]
Thanks for the example. I just wanted to see how it looked with the current theming.

This would be ~38kB of extra data being fetched on every page. While it might not be much, lets try to keep unnecessary fetches to a minimum?

Let's just keep these changes only in the files that need them, in the corresponding Django blocks (style/script)

**Comment by anirudhprabhakaran3** [comment]
yup, sounds good

**Review by nishant-nayak — APPROVED** [review]
LGTM! Thanks for running linters on the `base.html` file too!

**Pull request merged**
